### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'BatchTracer'

### ISSUE THREAD

**Issue by AlexiaJM** [yang-song/score_sde#1]
Hi Yang,

I'm getting the following error:
>   File "/localscratch/jolicoea.62752629.0/1/ScoreSDEMore/score_sde/losses.py", line 111, in loss_fn
>     losses = jnp.square(batch_mul(score, std) + z)
>   File "/localscratch/jolicoea.62752629.0/1/ScoreSDEMore/score_sde/utils.py", line 42, in batch_mul
>     return jax.vmap(lambda a, b: a * b)(a, b)
> TypeError: can't multiply sequence by non-int of type 'BatchTracer'

If I use chex.fake_pmap to be able to print inside the pmap, I see:

std:

> Traced<ShapedArray(float32[8])>with<BatchTrace(level=1/0)>
>   with val = DeviceArray([[ 0.21264698,  0.77755433,  0.27918625,  0.9448618 ,
>                            10.666621  ,  0.24025024, 12.233008  ,  3.626547  ]],            dtype=float32)
>        batch_dim = 0

z:

> Traced<ShapedArray(float32[8,32,32,3])>with<BatchTrace(level=1/0)>
>   with val = DeviceArray([[[[[-2.01293421e+00, -2.17641640e+00, -1.23569024e+00],
>                              [ 6.13737464e-01,  1.50414258e-01, -2.59380966e-01],
> ....

score:
> (Traced<ShapedArray(float32[8,32,32,3])>with<JVPTrace(level=3/0)>
>   with primal = Traced<ShapedArray(float32[8,32,32,3])>with<BatchTrace(level=1/0)>
>                   with val = DeviceArray([[[[[ 8.45328856e-08, -1.25030866e-07, -8.07002252e-08],
> ...

I tried to match your versions of libraries as much as possible. Same jax, flax, jaxlib version. Tensorflow_gpu=2.4.1. I use one GPU and config="configs/ncsnpp/cifar10_continuous_ve.py".

Update: If I do it on cifar10_continuous_vp.py it breaks here:

>   File "/localscratch/jolicoea.62752629.0/1/ScoreSDEMore/score_sde/models/utils.py", line 197, in score_fn
>     score = batch_mul(-model, 1. / std)
> TypeError: bad operand type for unary -: 'tuple'

**Comment by AlexiaJM** [comment]
On another note, is this a normal warning?
> 2021-02-27 07:39:13.931651: W tensorflow/core/kernels/data/cache_dataset_ops.cc:757] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.

**Comment by yang-song** [comment]
That's weird, I tried the following on my machine but couldn't reproduce your error:
`CUDA_VISIBLE_DEVICES=0 python main.py --mode train --config configs/ncsnpp/cifar10_continuous_ve.py --workdir test --config.training.batch_size=16`
It can train the model normally.

Some random thoughts:
1. Is your repo up to date? I was experimenting on my latest code pushed to github.
2. Did you install `jaxlib` properly? My `requirements.txt` is actually for TPUs. When installing `jaxlib` on GPUs, you will need to append CUDA version to `jaxlib` version number. See details here: https://github.com/google/jax#installation

The dataset warning you saw is not a normal warning. It can report such a warning when the program is interrupted for other reasons, such as the `TypeError` you encountered.

**Comment by AlexiaJM** [comment]
I have latest version of the repo and the following settings:
Python              3.8.2
numpy               1.19.2
ml-collections      0.1.0
tensorflow-gan      2.0.0
tensorflow-io       0.17.0
tensorflow-datasets 4.2.0
tensorflow-gpu      2.4.1
tensorflow-addons   0.11.2
tensorboard         2.4.1
absl-py             0.10.0
flax                0.3.1
jax                 0.2.8
jaxlib              0.1.59+cuda110

So the main differences are that I have tensorflow 2.4.1, flax=0.3.1, and that I use a GPU. I'll try to make a reproducible example in colab.

After a lot of experiments, I was able to replicate the error in google colab, it's because of flax=0.3.1. You can see here https://colab.research.google.com/drive/1zutmMjPjFIjtXo26McGdkRLy7spBZDtQ?usp=sharing.  So your code doesn't work with the newer flax.

I have a bug with flax=0.3.1 but its cuda related so its probably on my side, so I will close this issue. Thanks for helping.

**Comment by yang-song** [comment]
I actually fixed a bug in `flax` that will affect will our code. Didn't expect they have already incorporated this fix in 0.3.1.

**Comment by AlexiaJM** [comment]
Hi Yang,

I'm fully able to start my own analyses now, but I still get the warning which you say is not normal. I made a colab example so you can see that it (note that the colab example is extremely slow due to cpu, but you can see the warning output). 

https://colab.research.google.com/drive/1KHbQ_1WlZt9cNncrTw7K0oKv8K4-7lUw?usp=sharing

> 2021-03-02 16:21:08.521988: W tensorflow/core/kernels/data/cache_dataset_ops.cc:757] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.

**Comment by yang-song** [comment]
@AlexiaJM Have you tried running multiple iterations? With a single iteration I had the same warning as yours. But when `--config.training.n_iters` is large I didn't see the warning anymore.

**Comment by AlexiaJM** [comment]
I haven't had the time to run a full model, but that could explain it. Maybe niters needs to be large enough for one epoch.
