### ISSUE TITLE
which checkpoint for VP and deep-VP replicate the paper results

### ISSUE THREAD

**Issue by AlexiaJM** [yang-song/score_sde#11]
Hi Yang,

I just wanted to know which of the two checkpoints on https://drive.google.com/drive/folders/1F74y6G_AGqPw8DG5uhdO_Kf9DCX1jKfL and https://drive.google.com/drive/folders/1ikbUY_K4Rc2-lPz7baPxdEXtx76Xn5Ov replicate the results of the paper on Table 3?

Alexia

**Comment by yang-song** [comment]
`checkpoint_8` was for Table 3, and the other one for Table 2.

**Comment by AlexiaJM** [comment]
Thank you! See you at ICLR.
