### ISSUE TITLE
Why does the approximate equality in Eq.(24) holds?

### ISSUE THREAD

**Issue by chenweize1998** [yang-song/score_sde#17]
Hi! When I'm reading the proof that DDPM is a discretization of the VP-SDE in Appendix B of https://openreview.net/pdf?id=PxTIG12RRHS, I don't understand why Eq.(24) holds. I know that when $x\ll 1, \sqrt{1-x} \approx 1-x/2$. However, In Eq.(24), $\beta(t+\Delta t)\Delta t$ seems to not satisfy this condition, because $\beta(t)=N\beta_i$, and when $\Delta t\rightarrow 0, N\rightarrow \infty$. Could you explain why this approximate equality still holds?

**Comment by yuanzhi-zhu** [comment]
As mentioned in the paper around Eq.(24), you may notice that $\Delta t = 1/N$. Since $\beta_i \ll 1$ holds, $\beta(t+\Delta t)\Delta t$ actually satisfies the condition.

**Comment by chenweize1998** [comment]
Oh of course! Just forgot the condition $\beta_i\ll 1$. Thanks!

**Comment by mega-optimus** [comment]
Hi, on which page does it mention $\beta_i \ll 1$ ? Thanks!
