### ISSUE TITLE
Tips to train a model on a custom dataset

### ISSUE THREAD

**Issue by pbizimis** [yang-song/score_sde#2]
Hey,
I really like your work and I wanted to compare the results of an NCSNPP model to a GAN. I have a custom dataset of 31k images and I am using Google Colab (so 1x V100).

Do you have any helpful comments on how I should train an NCSNPP model with that specification? Best case, the resolution would be between 64 and 256.

Thanks!

**Comment by yang-song** [comment]
Thanks for your interest! 

Several tips:
1. When using the VESDE, set the maximum sigma to be the maximum pairwise distance between images in your dataset (see Technique 1 in https://arxiv.org/abs/2006.09011 for more details)
2. When memory is an issue, use a smaller batch size and set `config.training.n_jitted_steps=1`
3. You likely want to tune the `snr` parameter of the Langevin corrector for the best sampling performance.

Good luck!

**Comment by pbizimis** [comment]
Thanks a lot for your tips!
I have one question about the first one:

In your paper, it says "Technique 1 (Initial noise scale). Choose σ1 to be as large as the maximum Euclidean distance
between all pairs of training data points.". Do "all pairs of training data points" indicate two random images of my dataset? So for example:
- take out 2 random images of my 31.000
- calculate the Euclidean distance between those two
- repeat until no images are left
- take the median of my 15.500 distance values

Then you run annealed Langevin dynamics to sample from a mixture of Gaussian with 10000 components. With that, you are able to evaluate that σ1 with a value of 50 is better. Is there any code for that procedure? Also, if e.g. the median pairwise distance between all training images is around 18 just like for you, does that mean that I can also use a value of 50 for σ1? If so, do the median and σ1 have a linear relationship (so a median of 36 would mean a value of 100 for σ1)?

Thank you so much

**Comment by yang-song** [comment]
I actually meant taking the maximum of all pairwise distances, not the median. In general, you can always use an excessively large sigma_1, but making it too large also makes sampling slower and wastes computation on training score models for many very noisy images.

**Comment by pbizimis** [comment]
How would I calculate all pairwise distances for 31.000 images? My research shows Euclidean distance calculations for two images but not for a whole dataset.
Thanks!

**Comment by AlexiaJM** [comment]
You can  loop the dataset in mini-batch to get a reasonable approximation, https://github.com/AlexiaJM/AdversarialConsistentScoreMatching does it with option --compute_approximate_sigma_max. Either use that or use it to guide you in implementing it within this code.
