### ISSUE TITLE
Code for FID stats

### ISSUE THREAD

**Issue by AlexiaJM** [yang-song/score_sde#3]
Could you share the code for calculating the FID stats of a dataset and saving it? It seems that it does not recognize the FID stats from the original FID authors in https://github.com/bioinf-jku/TTUR.

**Comment by yang-song** [comment]
You can find the stats file we used in https://drive.google.com/file/d/106BAOiRpYYCPBu598ep_DQ_muwCMpwue/view?usp=sharing (inside the folder of our pre-trained checkpoints)

We computed the FID stats with `tfgan` on all CIFAR-10 training images. That was done on an internal Google colab that I no longer have access to, but should be straightforward to reproduce.

**Comment by AlexiaJM** [comment]
Thank you!
