### ISSUE TITLE
Checkpoint for CelebA-HQ

### ISSUE THREAD

**Issue by asanakoy** [yang-song/score_sde#4]
Hi guys,

first of all thank for the code!
I wonder if you could upload a pretrained checkpoint for CelebA-HQ ?
How long does it take to train on CelebA-HQ and how many GPUs are required?

Thanks,
Artsiom

**Comment by yang-song** [comment]
Unfortunately, Google's policy prevents us from releasing checkpoints trained on any human face dataset.

That said, I'm reproducing the results with personal resources, and will upload a checkpoint trained on FFHQ-1024 in the next few days. It takes 4 V100 (32GB) GPUs to train for around 2.5 weeks.

**Comment by yang-song** [comment]
Checkpoint for FFHQ 1024 is now available
